## Important note:
## If you want to run the integration tests, make sure that you go into the
## Travis settings for your repository, enable the "Limit concurrent jobs"
## option, and set the number of concurrent jobs to one (1).
## For more details, see https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs

branches:
  only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
  global:
    - AUTOMERGE_INTEGRATION_TEST_REPO="bcbi-test/automerge-integration-test-repo"
    # - JULIA_DEBUG="all"
  jobs:
    - AUTOMERGE_RUN_INTEGRATION_TESTS="false"
    - AUTOMERGE_RUN_INTEGRATION_TESTS="true"

git:
  depth: 99999999

julia:
  - "1.3"
  - "1" # "1" expands to the latest 1.y.z release of Julia
  - nightly

language: julia

notifications:
  email: false

os:
  - linux

script: julia --code-coverage -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; get(ENV, "AUTOMERGE_RUN_INTEGRATION_TESTS", "") == "true" && Codecov.submit(process_folder())'
